name: 'semver-action'
description: 'Generate a semantic version'

branding:
  color: purple
  icon: tag

inputs:
  main_branch_name:
    description: 'The main branch name'
    default: 'master'
    required: false
  develop_branch_name:
    description: 'The develop branch name'
    default: 'develop'
    required: false
  repo_dir:
    description: 'The repository path'
    default: '.'
    required: false
  debug:
    description: 'Enables debug mode'
    default: 'false'
    required: false
    
outputs:
  semver_tag:
    description: 'The calculdated semantic version'
  is_prerelease:
    description: 'True if calculated tag is pre-release'
  previous_tag:
    description: 'The tag used to calculate next semantic version'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.main_branch_name }}
    - ${{ inputs.develop_branch_name }}
    - ${{ inputs.repo_dir }}
    - ${{ inputs.debug }}
